public abstract class Vehicle{

    abstract void go();  //THIS COULD BE AN INTERFACE AND WE'D HAVE TO CHANGE EXTENDS FOR IMPLEMENTS IN THE SUBCLASSES
    //IT WORKS CUZ INTERFACE SIMPLY MAKES IT POSSIBLE TO INHERIT MULTIPLE CLASSES AND/OR JUST ONE CLASS, SO IT'S THE SAME
}
